import type { Project } from '~/types';

export const PROJECTS: Project[] = [
  {
    id: 9,
    title: 'Saddleback Robotics',
    description:
      'Built a ROS2-integrated Django GUI to control rover subsystems and visualize GPS and heading data, helping the team climb 3 ranks in competition.',
    featured: true,
    site: 'https://www.youtube.com/watch?v=2kkPbTSSpe0',
    source: 'https://github.com/SaddlebackCollegeRobotics',
    file: {
      src: '/portfolio/projects/saddleback-robotics.mp4',
      type: 'video',
    },
    visible: true,
    tags: [
      {
        id: 13,
        title: 'Python',
        logoName: 'python',
        url: 'https://docs.python.org/3',
        featured: true,
      },
      {
        id: 21,
        title: 'ROS2',
        logoName: null,
        url: 'https://docs.ros.org/en/humble/index.html',
        featured: false,
      },
      { id: 22, title: 'NAV2', logoName: null, url: null, featured: false },
      { id: 23, title: 'odrive', logoName: null, url: null, featured: false },
      { id: 24, title: 'Robotics', logoName: null, url: null, featured: false },
      {
        id: 25,
        title: 'Autonomous Vehicles',
        logoName: null,
        url: null,
        featured: false,
      },
      {
        id: 14,
        title: 'Linux',
        logoName: 'linux',
        url: 'https://github.com/torvalds/linux',
        featured: false,
      },
    ],
  },
  {
    id: 2,
    title: 'Street Fighter',
    description:
      'Built a networked Java multiplayer fighting game using a client server model with multithreading and synchronized game state across players.',
    featured: true,
    site: null,
    source: 'https://github.com/devloos/Street-Fighter',
    file: {
      src: '/portfolio/projects/street-fighter.mp4',
      type: 'video',
    },
    visible: true,
    tags: [
      { id: 15, title: 'JavaFX', logoName: null, url: null, featured: false },
      { id: 16, title: 'Maven', logoName: 'apachemaven', url: null, featured: false },
      {
        id: 12,
        title: 'Java',
        logoName: 'openjdk',
        url: 'https://www.tutorialspoint.com/java/java_documentation.htm',
        featured: true,
      },
    ],
  },
  {
    id: 5,
    title: 'Monster Quest',
    description:
      'Built a modular Python RPG with event driven architecture, sprite animations, and a smooth optimized game loop designed for easy expansion.',
    featured: true,
    site: null,
    source: 'https://github.com/devloos/monster-quest',
    file: {
      src: '/portfolio/projects/monster-quest.mp4',
      type: 'video',
    },
    visible: true,
    tags: [
      {
        id: 13,
        title: 'Python',
        logoName: 'python',
        url: 'https://docs.python.org/3',
        featured: true,
      },
      {
        id: 37,
        title: 'Tiled Map Editor',
        logoName: null,
        url: 'https://www.mapeditor.org/',
        featured: false,
      },
      {
        id: 38,
        title: 'Pygame',
        logoName: null,
        url: 'https://pyga.me/',
        featured: false,
      },
    ],
  },
  {
    id: 13,
    title: 'Devlos UI',
    description:
      'Vue and CSS framework-agnostic. Fully typed, tree-shakeable, and customizable. Built for performance, DX, and seamless integration. Published on npm.',
    featured: true,
    site: null,
    source: 'https://github.com/devloos/devlos-ui',
    file: null,
    visible: true,
    tags: [],
  },

  {
    id: 4,
    title: 'Sales System',
    description:
      'Built a terminal based C++ POS with role based permissions, receipt generation, and custom data structures using RAII for safety and performance.',
    featured: true,
    site: null,
    source: 'https://github.com/devloos/Sales-System',
    file: {
      src: '/portfolio/projects/sales-system.mp4',
      type: 'video',
    },
    visible: true,
    tags: [
      {
        id: 5,
        title: 'C++',
        logoName: 'cplusplus',
        url: 'https://en.cppreference.com/w',
        featured: true,
      },
      {
        id: 14,
        title: 'Linux',
        logoName: 'linux',
        url: 'https://github.com/torvalds/linux',
        featured: false,
      },
      {
        id: 18,
        title: 'CMake',
        logoName: 'cmake',
        url: 'https://cmake.org/cmake/help/latest',
        featured: false,
      },
    ],
  },
  {
    id: 3,
    title: 'Graphics Modeler',
    description:
      'Built a 2D graphics library in C++ with Qt, applying inheritance and polymorphism to power a GUI for manipulating shapes and object properties.',
    featured: false,
    site: null,
    source: 'https://github.com/devloos/Graphics-Modeler',
    file: {
      src: '/portfolio/projects/graphics-modeler.mp4',
      type: 'video',
    },
    visible: true,
    tags: [
      {
        id: 5,
        title: 'C++',
        logoName: 'cplusplus',
        url: 'https://en.cppreference.com/w',
        featured: true,
      },
      {
        id: 14,
        title: 'Linux',
        logoName: 'linux',
        url: 'https://github.com/torvalds/linux',
        featured: false,
      },
      { id: 17, title: 'QT', logoName: 'qt', url: 'https://doc.qt.io', featured: false },
      {
        id: 18,
        title: 'CMake',
        logoName: 'cmake',
        url: 'https://cmake.org/cmake/help/latest',
        featured: false,
      },
    ],
  },
  {
    id: 15,
    title: 'DoodleMorph',
    description:
      'An AI-powered web app where you draw a quick sketch and watch it morph into a fully generated artwork using Diffusers and Florence-2, built with Vue, Flask, and Tailwind.',
    featured: false,
    site: null,
    source: 'https://github.com/devloos/DoodleMorph',
    file: null,
    visible: true,
    tags: [],
  },
  {
    id: 8,
    title: 'Terminal Snake Game',
    description:
      'Built a modular terminal based Snake game in modern C++ using ncurses, cleanly separating game logic, rendering, and input handling.',
    featured: false,
    site: null,
    source: 'https://github.com/devloos/Snake-Game',
    file: null,
    visible: true,
    tags: [
      {
        id: 5,
        title: 'C++',
        logoName: 'cplusplus',
        url: 'https://en.cppreference.com/w',
        featured: true,
      },
      { id: 45, title: 'Tui', logoName: null, url: null, featured: false },
      { id: 46, title: 'Ncurses', logoName: null, url: null, featured: false },
      {
        id: 18,
        title: 'CMake',
        logoName: 'cmake',
        url: 'https://cmake.org/cmake/help/latest',
        featured: false,
      },
    ],
  },
  {
    id: 11,
    title: 'Standard Template Library',
    description:
      'Built a custom C++ STL style library implementing core data structures from scratch to mirror and extend standard container behavior.',
    featured: false,
    site: null,
    source: 'https://github.com/devloos/STL',
    file: null,
    visible: true,
    tags: [
      {
        id: 5,
        title: 'C++',
        logoName: 'cplusplus',
        url: 'https://en.cppreference.com/w',
        featured: true,
      },
      { id: 47, title: 'Library', logoName: null, url: null, featured: false },
      {
        id: 14,
        title: 'Linux',
        logoName: 'linux',
        url: 'https://github.com/torvalds/linux',
        featured: false,
      },
    ],
  },
  {
    id: 6,
    title: 'Vue.js Snippets (Vscode Extension)',
    description:
      'Built a Vue 3 productivity extension for VS Code used by over 15,000 developers to speed up component and template creation.',
    featured: false,
    site: 'https://marketplace.visualstudio.com/items?itemName=devlos.vuejs-snippets',
    source: 'https://github.com/devloos/vuejs-snippets',
    file: null,
    visible: true,
    tags: [
      {
        id: 3,
        title: 'Vue.js',
        logoName: 'vuedotjs',
        url: 'https://vuejs.org/guide/introduction.html',
        featured: true,
      },
      { id: 39, title: 'Vscode', logoName: null, url: null, featured: false },
      { id: 40, title: 'Extensions', logoName: null, url: null, featured: false },
    ],
  },
  {
    id: 7,
    title: 'Raycast Format JSON Extension',
    description:
      'Built a Raycast extension with 30K+ users that parses and formats JSON with customizable indentation for fast everyday workflows.',
    featured: false,
    site: 'https://www.raycast.com/destiner/json-format',
    source:
      'https://github.com/raycast/extensions/tree/de2627a96b88691ce3d523f23dc778a651cd8368/extensions/json-format',
    file: null,
    visible: true,
    tags: [
      { id: 42, title: 'Typescript', logoName: null, url: null, featured: false },
      { id: 43, title: 'Raycast', logoName: null, url: null, featured: false },
      { id: 44, title: 'Extensions', logoName: null, url: null, featured: false },
      { id: 41, title: 'React.js', logoName: 'react', url: null, featured: true },
    ],
  },
  {
    id: 1,
    title: 'El Andariego',
    description:
      'Built a responsive website for a local food truck with i18n, Square online ordering, automated emails, and cron driven menu updates to support growth.',
    featured: false,
    site: 'https://www.elandariegotruck.com/',
    source: 'https://github.com/devloos/El-Andariego',
    file: {
      src: '/portfolio/projects/el-andariego-1704676212150.mp4',
      type: 'video',
    },
    visible: true,
    tags: [
      {
        id: 3,
        title: 'Vue.js',
        logoName: 'vuedotjs',
        url: 'https://vuejs.org/guide/introduction.html',
        featured: true,
      },
      {
        id: 6,
        title: 'Tailwind CSS',
        logoName: 'tailwindcss',
        url: 'https://tailwindcss.com/docs/installation',
        featured: true,
      },
      {
        id: 10,
        title: 'MongoDB',
        logoName: 'mongodb',
        url: 'https://www.mongodb.com/docs',
        featured: true,
      },
      {
        id: 1,
        title: 'Typescript',
        logoName: 'typescript',
        url: 'https://www.typescriptlang.org/docs/',
        featured: true,
      },
      {
        id: 9,
        title: 'Laravel',
        logoName: 'laravel',
        url: 'https://laravel.com/docs/10.x',
        featured: false,
      },
    ],
  },
  {
    id: 10,
    title: 'LeetCode',
    description:
      'A curated collection of solved LeetCode problems with clear explanations and time and space complexity breakdowns.',
    featured: false,
    site: 'https://leetcode.com/u/devlos',
    source: 'https://github.com/devloos/Leetcode',
    file: null,
    visible: true,
    tags: [
      {
        id: 5,
        title: 'C++',
        logoName: 'cplusplus',
        url: 'https://en.cppreference.com/w',
        featured: true,
      },
      {
        id: 13,
        title: 'Python',
        logoName: 'python',
        url: 'https://docs.python.org/3',
        featured: true,
      },
      { id: 27, title: 'Algorithms', logoName: null, url: null, featured: false },
      {
        id: 1,
        title: 'Typescript',
        logoName: 'typescript',
        url: 'https://www.typescriptlang.org/docs/',
        featured: true,
      },
    ],
  },
  {
    id: 12,
    title: 'Shortcut Manager',
    description:
      'Built a shortcut management extension that lets users create, customize, and resolve conflicting hotkeys for a smoother workflow.',
    featured: false,
    site: null,
    source: 'https://github.com/devloos/Shortcut-Manager',
    file: null,
    visible: true,
    tags: [
      { id: 42, title: 'Typescript', logoName: null, url: null, featured: false },
      { id: 43, title: 'Raycast', logoName: null, url: null, featured: false },
      { id: 44, title: 'Extensions', logoName: null, url: null, featured: false },
      { id: 41, title: 'React.js', logoName: 'react', url: null, featured: true },
    ],
  },
  {
    id: 14,
    title: 'ZMK Config',
    description: 'Custom ZMK config for the Corne Wireless keyboard.',
    featured: false,
    site: null,
    source: 'https://github.com/devloos/corne-wireless-view-zmk-config',
    file: null,
    visible: true,
    tags: [],
  },
  {
    id: 16,
    title: 'Runner Gunner',
    description: "It's a game where you run and gun! Using Raylib and C++.",
    featured: false,
    site: null,
    source: 'https://github.com/devloos/Runner-Gunner',
    file: null,
    visible: true,
    tags: [],
  },
] as const;
